#!/usr/bin/env bash
# This script installs a nginx web server

sudo apt update
sudo apt install nginx -y
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null 2>&1
sudo service nginx restart
