#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
