#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

sudo apt-get -y install nginx
# 1 Return a page with 'Hello World' text
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# redirect
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "53s|.*|$redirect|" /etc/nginx/sites-enabled/default

# creates custo
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sudo sed -i "47s|.*| \n\terror_page 404 /error404.html;\n|" /etc/nginx/sites-en
bled/default
sudo /etc/init.d/nginx restart
