#!/usr/bin/env bash
# Install haproxy and config 2 server
apt-get update
apt-get -y install haproxy=1.6.\*
echo "ENABLED=1" >> /etc/default/haproxy
sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 1231-web-01 34.198.248.145:80 check\n\tserver 1231-web-02 54.89.38.100:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
