#!/usr/bin/env bash
cd /etc/nginx/sites-enabled/ || exit;
# Delete the default                                           
rm default;                                                           
# Create symbolic link to the deafult file in sites-availabl
ln -s /etc/nginx/sites-available/default default;
# Restart Nginx
service nginx restart
