#!/usr/bin/env bash
# fix nginx listening on port 80
cd /etc/nginx/sites-enabled/ || exit;
# Delete the default file
rm default;
# Create symbolic link to the deafult file in sites-available
ln -s /etc/nginx/sites-available/default default;
service nginx restart
