#!/usr/bin/env bash
# script that run software as another user.
chmod 444 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
